### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by AoifeHughes** [alan-turing-institute/SARS-CoV-2-UK-Wastewater-TDS#1]
# TODOs 

- [ ] Add some background information
- [ ] Proof read all sections and tidy up English 
- [ ] Clean up data used 
- [ ] Finish analysis
- [ ] Data loading section
- [ ] Get England plotly displaying properly 
- [ ] Plot spatial data for population
- [ ] Analyse region variation over time for wastewater gc/l
  - [ ] Analyse as a spatial-temporal problem
- [ ] Incorporate weather data 
  - [ ] Add cleaning method for weather data from MET office
- [ ] Incorporate COVID19 testing data

**Comment by AoifeHughes** [comment]
- [ ] Add conclusion
- [ ] Check all figure headings and axis labels are good!
- [ ] Add some references to things?
